In [2]:
import numpy as np

In [12]:
data = np.array([1,2,3,2])
data = data*2
print(data)

print('Var of data:', data.var())
print('Std of data:', data.std().round(2))

[2 4 6 4]
Var of data: 2.0
Std of data: 1.41


In [16]:
x = np.array([1, 2])
y = np.array([5,4])
print(data)

print('Var of data:', x.var())
print('Std of data:', data.std().round(2))

[[1 5]
 [2 4]]
Var of data: 0.25
Std of data: 1.58


In [37]:
data = np.array([[1,-1],[1, -1]])
print(np.cov(data)/2)

[[1. 1.]
 [1. 1.]]
