In [2]:
# PACKAGE: DO NOT EDIT THIS CELL
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
matplotlib.style.use('fivethirtyeight')
from sklearn.datasets import fetch_lfw_people, fetch_olivetti_faces
import time
import timeit

In [5]:
# From Coursera
X_test = np.arange(6).reshape(2,3)
expected_test_mean = np.array([1., 4.]).reshape(-1, 1)
expected_test_cov = np.array([[2/3., 2/3.], [2/3.,2/3.]])
print('X:\n', X_test)
print('Expected mean:\n', expected_test_mean)
print('Expected covariance:\n', expected_test_cov)


X:
 [[0 1 2]
 [3 4 5]]
Expected mean:
 [[1.]
 [4.]]
Expected covariance:
 [[0.66666667 0.66666667]
 [0.66666667 0.66666667]]


In [8]:
D, N = X_test.shape
print('Dimensionality is: ',D)
print('Number of samples is: ',N)

Dimensionality is:  2
Number of samples is:  3


In [16]:
# Find mean and covariance using built in numpy functions
mean = np.mean(X_test, axis = 1).reshape(D,1)
print('The mean is: ',mean)

cov = np.cov(X_test,bias=True)
print('The cov is: ', cov)

The mean is:  [[1.]
 [4.]]
The cov is:  [[0.66666667 0.66666667]
 [0.66666667 0.66666667]]


In [36]:
# Find mean and covariance using for loops
mean = np.zeros((D,1))
print('Mean starts as: ',mean)
for n in range(N):
    mean = mean + X_test[:,n].reshape(D,1)
mean = mean/N
print(mean)

Mean starts as:  [[0.]
 [0.]]
[[1.]
 [4.]]


In [26]:
X_test[:,1] + X_test[:,2] 

array([3, 9])

In [50]:
random = np.random.RandomState(42)
A = random.randn(4,4)
b = random.randn(4,1)
X = random.randn(4,100) # D = 4, N = 100
X1 = (A @ X) + b  # applying affine transformation to each sample in X

In [51]:
print('X1 mean is ',np.mean(X1).round(3), 'and X mean is ',np.mean(X).round(3))


X1 mean is  -0.784 and X mean is  0.029


In [55]:
A  = np.array([1,2])
B = np.array([2,1])

In [60]:
import numpy.linalg as la

In [64]:
la.norm(A) - la.norm(B)

0.0